#!/bin/sh
echo "ENVIRONMENT VARIABLES, BACKEND:"

# DB: DATABASE_URL
echo "DATABASE_URL:"
read DATABASE_URL

# DB: DIRECT_URL
echo "DIRECT_URL:"
read DIRECT_URL

# FIREBASE: FIREBASE_TYPE
echo "FIREBASE_TYPE:"
read FIREBASE_TYPE

# FIREBASE: FIREBASE_PROJECT_ID
echo "FIREBASE_PROJECT_ID:"
read FIREBASE_PROJECT_ID

# FIREBASE: FIREBASE_PRIVATE_KEY_ID
echo "FIREBASE_PRIVATE_KEY_ID:"
read FIREBASE_PRIVATE_KEY_ID

# FIREBASE: FIREBASE_PRIVATE_KEY
echo "FIREBASE_PRIVATE_KEY:"
read FIREBASE_PRIVATE_KEY

# FIREBASE: FIREBASE_CLIENT_EMAIL
echo "FIREBASE_CLIENT_EMAIL:"
read FIREBASE_CLIENT_EMAIL

# FIREBASE: FIREBASE_CLIENT_ID
echo "FIREBASE_CLIENT_ID:"
read FIREBASE_CLIENT_ID

# FIREBASE: FIREBASE_AUTH_URI
echo "FIREBASE_AUTH_URI:"
read FIREBASE_AUTH_URI

# FIREBASE: FIREBASE_TOKEN_URI
echo "FIREBASE_TOKEN_URI:"
read FIREBASE_TOKEN_URI

# FIREBASE: FIREBASE_AUTH_PROVIDER_CERT
echo "FIREBASE_AUTH_PROVIDER_CERT:"
read FIREBASE_AUTH_PROVIDER_CERT

# FIREBASE: FIREBASE_CLIENT_CERT_URL
echo "FIREBASE_CLIENT_CERT_URL:"
read FIREBASE_CLIENT_CERT_URL

# Override env file
cat > backend/.env <<EOL
# Database
DATABASE_URL="$DATABASE_URL"
DIRECT_URL="$DIRECT_URL"

# Firebase authentication
FIREBASE_TYPE="$FIREBASE_TYPE"
FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID"
FIREBASE_PRIVATE_KEY_ID="$FIREBASE_PRIVATE_KEY_ID"
FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY"
FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL"
FIREBASE_CLIENT_ID="$FIREBASE_CLIENT_ID"
FIREBASE_AUTH_URI="$FIREBASE_AUTH_URI"
FIREBASE_TOKEN_URI="$FIREBASE_TOKEN_URI"
FIREBASE_AUTH_PROVIDER_CERT="$FIREBASE_AUTH_PROVIDER_CERT"
FIREBASE_CLIENT_CERT_URL="$FIREBASE_CLIENT_CERT_URL"
EOL

