#!/bin/sh
printf "\e[1;34mENVIRONMENT VARIABLES, BACKEND:\e[0m\n"

# DB: DATABASE_URL
printf "\e[34mDATABASE_URL:\e[0m\n"
read DATABASE_URL

# DB: DIRECT_URL
printf "\e[34mDIRECT_URL:\e[0m\n"
read DIRECT_URL

# FIREBASE: FIREBASE_TYPE
printf "\e[34mFIREBASE_TYPE:\e[0m\n"
read FIREBASE_TYPE

# FIREBASE: FIREBASE_PROJECT_ID
printf "\e[34mFIREBASE_PROJECT_ID:\e[0m\n"
read FIREBASE_PROJECT_ID

# FIREBASE: FIREBASE_PRIVATE_KEY_ID
printf "\e[34mFIREBASE_PRIVATE_KEY_ID:\e[0m\n"
read FIREBASE_PRIVATE_KEY_ID

# FIREBASE: FIREBASE_PRIVATE_KEY
printf "\e[34mFIREBASE_PRIVATE_KEY:\e[0m\n"
read FIREBASE_PRIVATE_KEY

# FIREBASE: FIREBASE_CLIENT_EMAIL
printf "\e[34mFIREBASE_CLIENT_EMAIL:\e[0m\n"
read FIREBASE_CLIENT_EMAIL

# FIREBASE: FIREBASE_CLIENT_ID
printf "\e[34mFIREBASE_CLIENT_ID:\e[0m\n"
read FIREBASE_CLIENT_ID

# FIREBASE: FIREBASE_AUTH_URI
printf "\e[34mFIREBASE_AUTH_URI:\e[0m\n"
read FIREBASE_AUTH_URI

# FIREBASE: FIREBASE_TOKEN_URI
printf "\e[34mFIREBASE_TOKEN_URI:\e[0m\n"
read FIREBASE_TOKEN_URI

# FIREBASE: FIREBASE_AUTH_PROVIDER_CERT
printf "\e[34mFIREBASE_AUTH_PROVIDER_CERT:\e[0m\n"
read FIREBASE_AUTH_PROVIDER_CERT

# FIREBASE: FIREBASE_CLIENT_CERT_URL
printf "\e[34mFIREBASE_CLIENT_CERT_URL:\e[0m\n"
read FIREBASE_CLIENT_CERT_URL

# Override env file
cat > backend/.env <<EOL
# Database
DATABASE_URL="$DATABASE_URL"
DIRECT_URL="$DIRECT_URL"

# Firebase authentication
FIREBASE_TYPE="$FIREBASE_TYPE"
FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID"
FIREBASE_PRIVATE_KEY_ID="$FIREBASE_PRIVATE_KEY_ID"
FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY"
FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL"
FIREBASE_CLIENT_ID="$FIREBASE_CLIENT_ID"
FIREBASE_AUTH_URI="$FIREBASE_AUTH_URI"
FIREBASE_TOKEN_URI="$FIREBASE_TOKEN_URI"
FIREBASE_AUTH_PROVIDER_CERT="$FIREBASE_AUTH_PROVIDER_CERT"
FIREBASE_CLIENT_CERT_URL="$FIREBASE_CLIENT_CERT_URL"
EOL

