#!/bin/sh
echo "ENVIRONMENT VARIABLES, FRONTEND:"

# DB: VITE_EXPRESS_BASE_URL
echo "VITE_EXPRESS_BASE_URL:"
read VITE_EXPRESS_BASE_URL

# DB: VITE_API_KEY
echo "VITE_API_KEY:"
read VITE_API_KEY

# DB: VITE_AUTH_DOMAIN
echo "VITE_AUTH_DOMAIN:"
read VITE_AUTH_DOMAIN

# DB: VITE_PROJECT_ID
echo "VITE_PROJECT_ID:"
read VITE_PROJECT_ID

# DB: VITE_STORAGE_BUCKET
echo "VITE_STORAGE_BUCKET:"
read VITE_STORAGE_BUCKET

# DB: VITE_MESSAGING_SENDER_ID
echo "VITE_MESSAGING_SENDER_ID:"
read VITE_MESSAGING_SENDER_ID

# DB: VITE_APP_ID
echo "VITE_APP_ID:"
read VITE_APP_ID

# DB: VITE_MEASUREMENT_ID
echo "VITE_MEASUREMENT_ID:"
read VITE_MEASUREMENT_ID

# Override env file
cat > frontend/.env <<EOL
# Express
VITE_EXPRESS_BASE_URL="$VITE_EXPRESS_BASE_URL"

# Firebase authentication
VITE_API_KEY="$VITE_API_KEY"
VITE_AUTH_DOMAIN="$VITE_AUTH_DOMAIN"
VITE_PROJECT_ID="$VITE_PROJECT_ID"
VITE_STORAGE_BUCKET="$VITE_STORAGE_BUCKET"
VITE_MESSAGING_SENDER_ID="$VITE_MESSAGING_SENDER_ID"
VITE_APP_ID="$VITE_APP_ID"
VITE_MEASUREMENT_ID="$VITE_MEASUREMENT_ID"
EOL